Solutions/WebApplication/src/java-generated/com/mobile/dto/Device.java
/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.mobile.dto;

import java.sql.Timestamp;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class Device extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "device";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private Integer deviceId;
    private Integer registeredUserId;
    private String subscriber;
    private Timestamp createdDate;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public Device() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Integer getDeviceId() {
        return deviceId;
    }

    public void setDeviceId( Integer _val) {
        this.deviceId = _val;
    }

    public Integer getRegisteredUserId() {
        return registeredUserId;
    }

    public void setRegisteredUserId( Integer _val) {
        this.registeredUserId = _val;
    }

    public String getSubscriber() {
        return subscriber;
    }

    public void setSubscriber( String _val) {
        this.subscriber = _val;
    }

    public Timestamp getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate( java.util.Date _val ) {
        setCreatedDate((Timestamp)( _val != null ? new Timestamp( _val.getTime()) : null ));
    }

    public void setCreatedDate( Timestamp _val) {
        this.createdDate = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof Device))) return false;

        Device _o = (Device) _other;

        if ( deviceId == null ) {
            if ( _o.deviceId != null ) return false;
        }
        else if ( _o.deviceId == null || deviceId.intValue() != _o.deviceId.intValue()) return false;

        if ( registeredUserId == null ) {
            if ( _o.registeredUserId != null ) return false;
        }
        else if ( _o.registeredUserId == null || registeredUserId.intValue() != _o.registeredUserId.intValue()) return false;

        if ( subscriber == null ) {
            if ( _o.subscriber != null ) return false;
        }
        else if ( _o.subscriber == null || !subscriber.equals( _o.subscriber )) return false;

        if ( createdDate == null ) {
            if ( _o.createdDate != null ) return false;
        }
        else if ( _o.createdDate == null || createdDate.getTime() != _o.createdDate.getTime()) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = 2043677302; // = "Device".hashCode()
        _ret += deviceId == null ? 0 : deviceId;
        _ret = 29 * _ret + (registeredUserId == null ? 0 : registeredUserId);
        _ret = 29 * _ret + (subscriber == null ? 0 : subscriber.hashCode());
        _ret = 29 * _ret + (createdDate == null ? 0 : (int)createdDate.getTime());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "deviceId", deviceId );
        append( sb, "registeredUserId", registeredUserId );
        append( sb, "subscriber", subscriber );
        append( sb, "createdDate", createdDate );
    }
}

Solutions/WebApplication/src/java/web/bean/CrashReportBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web.bean;

import com.mobile.dto.Crash;
import data.helper.CategoryHelper;
import data.helper.CrashHelper;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import web.WebConstants;

/**
 *
 * @author HSC314
 */
@ManagedBean
@SessionScoped
public class CrashReportBean {

    private List<com.mobile.dto.Crash> crashs;
    private final static Logger LOGGER = Logger.getLogger(CategoryHelper.class
            .getName());
    private Crash selectedCrash;

    public Crash getSelectedCrash() {
        return selectedCrash;
    }

    private String rtnEditMsg;

    public String getRtnEditMsg() {
        return rtnEditMsg;
    }

    public void setRtnEditMsg(String rtnEditMsg) {
        this.rtnEditMsg = rtnEditMsg;
    }

    public void setSelectedCrash(Crash selectedCrash) {
        this.selectedCrash = selectedCrash;
    }

    public List<com.mobile.dto.Crash> getCrashs() {
        LOGGER.log(Level.OFF, "start getRegisterUsers ");
        crashs = CrashHelper.findAll();

        Collections.sort(crashs, new Comparator<Crash>() {

            @Override
            public int compare(Crash o1, Crash o2) {
                int compareInt = o2.getCreatedDate().compareTo(o1.getCreatedDate());
                return compareInt;

            }
        });

        LOGGER.log(Level.OFF, "end getRegisterUsers ");
        return crashs;
    }

    public void deleteActionListener() {
        FacesContext fc = FacesContext.getCurrentInstance();
        if (CrashHelper.deleteAll() > 0) {
            fc.addMessage(null, new FacesMessage("Successful", WebConstants.CRASHYESDELETEMSG));
        } else {
            fc.addMessage(null, new FacesMessage("Unsuccessful", WebConstants.CRASHNODELETEMSG));
        }
    }

    public void setRegisterUsers(List<com.mobile.dto.Crash> crashs) {
        this.crashs = crashs;
    }
}

Solutions/WebApplication/src/java/web/bean/DepartmentBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web.bean;

import com.mobile.dto.Department;
import data.extender.DepartmentExtender;
import data.helper.DepartmentHelper;
import data.helper.GeoLocation;
import data.helper.GeoLocationHelper;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.ConfigurableNavigationHandler;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import org.apache.commons.io.IOUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.UploadedFile;
import util.IconBase64;
import web.WebConstants;

/**
 *
 * @author HSC314
 */
@ManagedBean
public class DepartmentBean implements Serializable {


    private final static Logger LOGGER = Logger.getLogger(DepartmentBean.class
            .getName());

    // List of departments 
    private List<Department> departmentList;

    public List<Department> getDepartmentList() {
        FacesContext fc = FacesContext.getCurrentInstance();
        departmentList = DepartmentHelper.findAll();
        fc.getExternalContext().getSessionMap().put(WebConstants.DEPARTMENTBEAN_DEPTLIST, departmentList);
        return departmentList;
    }

    public void setDepartmentList(List<Department> departmentList) {
        this.departmentList = departmentList;
    }

    private List<DepartmentExtender> departmentExtenderList;

    public List<DepartmentExtender> getDepartmentExtenderList() {
        FacesContext fc = FacesContext.getCurrentInstance();
        departmentExtenderList = DepartmentHelper.findAllExtender();
        fc.getExternalContext().getSessionMap().put(WebConstants.DEPARTMENTBEAN_DEPTEXTLIST, departmentExtenderList);
        return departmentExtenderList;
    }

    public void setDepartmentExtenderList(List<DepartmentExtender> departmentExtenderList) {
        this.departmentExtenderList = departmentExtenderList;
    }

    // department used for adds
    private Department department = new Department();

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    // deparment used for selecting from list
    private DepartmentExtender selectedDepartment;

    public DepartmentExtender getSelectedDepartment() {
        FacesContext fc = FacesContext.getCurrentInstance();
        selectedDepartment = (DepartmentExtender) fc.getExternalContext().getSessionMap().get(WebConstants.DEPARTMENTBEAN_SELECTEDDEPT);
        return selectedDepartment;
    }

    public void setSelectedDepartment(DepartmentExtender selectedDepartment) {
        this.selectedDepartment = selectedDepartment;
    }

    // streamed content icons for displaying
//    public StreamedContent getIconForList() {
//        FacesContext fc = FacesContext.getCurrentInstance();
//        if (fc.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
//            return new DefaultStreamedContent();
//        } else {
//            String index = fc.getExternalContext().getRequestParameterMap().get("departmentIndex");
//            List<DepartmentExtender> deptextlist
//                    = (List<DepartmentExtender>) fc.getExternalContext().getSessionMap().get(WebConstants.DEPARTMENTBEAN_DEPTEXTLIST);
//            return deptextlist.get(Integer.valueOf(index)).getIconImage();
//        }
//    }
    public String getIconForAddString() {
        UploadedFile iconFile = getIconFile();
        if (iconFile != null) {
            return IconBase64.encodeToString(iconFile);
        } else {
            return "";
        }
    }

//    public StreamedContent getIconForAdd() {
//        FacesContext fc = FacesContext.getCurrentInstance();
//        if (fc.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
//            return new DefaultStreamedContent();
//        } else {
//            UploadedFile iconFile = getIconFile();
//            if (iconFile != null) {
//                try {
//                    return new DefaultStreamedContent(iconFile.getInputstream(), iconFile.getContentType());
//                } catch (IOException ex) {
//                    Logger.getLogger(DepartmentBean.class.getName()).log(Level.SEVERE, null, ex);
//                    return new DefaultStreamedContent();
//                }
//            } else {
//                return new DefaultStreamedContent();
//            }
//        }
//    }
    public String getIconForEditString() {
        UploadedFile iconFile = getIconFile();
        if (iconFile != null) {
            return IconBase64.encodeToString(iconFile);
        } else {
            String iconStr = "";
            if (selectedDepartment != null) {
                iconStr = selectedDepartment.getIconstring();
            }
            return iconStr;
        }

    }

//    public StreamedContent getIconForEdit() {
//        FacesContext fc = FacesContext.getCurrentInstance();
//        if (fc.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
//            return new DefaultStreamedContent();
//        } else {
//            UploadedFile iconFile = getIconFile();
//            if (iconFile != null) {
//                try {
//                    return new DefaultStreamedContent(iconFile.getInputstream(), iconFile.getContentType());
//                } catch (IOException ex) {
//                    Logger.getLogger(DepartmentBean.class.getName()).log(Level.SEVERE, null, ex);
//                    return new DefaultStreamedContent();
//                }
//            } else {
//                if (getSelectedDepartment() != null) {
//                    if (selectedDepartment.getIcon() != null) {
//                        return new DefaultStreamedContent(new ByteArrayInputStream(selectedDepartment.getIcon()), selectedDepartment.getIcontype());
//                    }
//                }
//                return new DefaultStreamedContent();
//
//            }
//        }
//    }
    // uploaded file used for icon
    public UploadedFile getIconFile() {
        FacesContext fc = FacesContext.getCurrentInstance();
        UploadedFile iconFile
                = (UploadedFile) fc.getExternalContext().getSessionMap().get(WebConstants.DEPARTMENT_ICONFILE);
        return iconFile;
    }

    public void setIconFile(UploadedFile iconFile) {
        FacesContext fc = FacesContext.getCurrentInstance();
        if (iconFile == null) {
            fc.getExternalContext().getSessionMap().remove(WebConstants.DEPARTMENT_ICONFILE);
        } else {
            fc.getExternalContext().getSessionMap().put(WebConstants.DEPARTMENT_ICONFILE, iconFile);
        }
    }

    // add function
    public String add() {
        LOGGER.log(Level.OFF, "start add");

        UploadedFile iconFile = getIconFile();
        if (iconFile != null) {
            LOGGER.log(Level.OFF, "  start add icon");

            this.department.setIconstring(IconBase64.encodeToString(iconFile));

            byte[] iconBytes = null;
            String iconType = "";

            try {
                iconBytes = IOUtils.toByteArray(iconFile.getInputstream());

            } catch (IOException ex) {
                Logger.getLogger(DepartmentBean.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            iconType = iconFile.getContentType();

            this.department.setIcon(iconBytes);
            this.department.setIcontype(iconType);

            setIconFile(null);  // clear stored iconfile once used

            LOGGER.log(Level.OFF, "  end add icon");

        } //if (iconFile != null)      

        GeoLocationHelper geoLocationHelper = new GeoLocationHelper();
        String location = null;
        if (selectedDepartment == null || selectedDepartment.getLocation() == null) {
            location = this.department.getLocation();
        }
        GeoLocation geoLocation = geoLocationHelper.getGeoLocation(location);

        this.department.setLatitude(geoLocation.latitude);
        this.department.setLongitude(geoLocation.longitude);

        this.department = DepartmentHelper.add(this.department);

        LOGGER.log(Level.OFF, "end add ");

        return WebConstants.DEPARTMENTS_PAGE;

    } //add

    // initializae values for the add department function
    public void addDepartmentInitializer(ActionEvent event) {
        setIconFile(null);  // clear stored iconfile once used        
    }

    // update function
    public String update() {
        LOGGER.log(Level.OFF, "start update");

        UploadedFile iconFile = getIconFile();
        if (iconFile != null) {
            LOGGER.log(Level.OFF, "  start update icon");

            this.selectedDepartment.setIconstring(IconBase64.encodeToString(iconFile));

            byte[] iconBytes = null;
            String iconType = "";

            try {
                iconBytes = IOUtils.toByteArray(iconFile.getInputstream());

            } catch (IOException ex) {
                Logger.getLogger(DepartmentBean.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            iconType = iconFile.getContentType();

            this.selectedDepartment.setIcon(iconBytes);
            this.selectedDepartment.setIcontype(iconType);


Solutions/WebApplication/web/admin/a.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 
    <h:head>
        <title>Edit Organization</title>
    </h:head>
    <body>
        <h:form>
                
                    <p:panel header="All fields are required and must contain valid information">
                        <h:panelGrid columns="2" style="height: 96px; width:456px;">

                            <h:outputText value="Organization:" style="font-weight: bold"/>
                            <h:outputText value="#{departmentBean.selectedDepartment.organizationName}"
                                          style="width: 300px"/>   

                            <h:outputText value="Name:" style="font-weight: bold"/>
                            <h:inputText id="nameInputText" 
                                         required="true" 
                                         style="width: 300px"
                                         value="#{departmentBean.selectedDepartment.name}" 
                                         requiredMessage="Please enter name" 
                                         validatorMessage="Name must be greater than 3 and less than 40">
                                <f:validateLength minimum="3" 
                                                  maximum="40" />
                            </h:inputText>

                            <h:outputText value="Email:" style="font-weight: bold"/>
                            <h:inputText id="emailInputText" 
                                         required="true" 
                                         style="width: 300px"
                                         value="#{departmentBean.selectedDepartment.email}" 
                                         requiredMessage="Please enter email" 
                                         validatorMessage="Invalid email format">
                                <f:validateLength minimum="6" maximum="50" />
                                <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                            </h:inputText>

                            <h:outputText value="Location:" style="font-weight: bold"/>
                            <h:inputText id="locationInputText" 
                                         required="true" 
                                         style="width: 300px"
                                         value="#{departmentBean.selectedDepartment.location}" 
                                         requiredMessage="Please enter address" 
                                         validatorMessage="Address must be greater than 3 and less than 60">
                                <f:validateLength minimum="3" maximum="60" />  
                            </h:inputText> 

                            <h:outputText value="General Information:" style="font-weight: bold"/>
                            <h:inputTextarea id="generalInformationInputText" 
                                             required="true" 
                                             rows="15" 
                                             cols="40"
                                             value="#{departmentBean.selectedDepartment.generalInformation}" 
                                             requiredMessage="Please enter general information">
                            </h:inputTextarea>

                            <h:outputText value="Icon:" style="font-weight: bold"/>
                            <p:panelGrid columns="2">
                                <h:graphicImage id="IconImage"
                                                value="#{departmentBean.iconForEditString}" height="48px"/>
                                <p:fileUpload fileUploadListener="#{departmentBean.handleFileUploadDepartment}" 
                                              mode="advanced"
                                              auto="True" 
                                              update="IconImage" 
                                              sizeLimit="10000" 
                                              allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
                            </p:panelGrid>
                        </h:panelGrid>
                        <h:commandButton type="submit" value="Update" action="#{departmentBean.update}" />
                        <h:commandButton type="submit" value="Delete" action="#{departmentBean.delete(departmentbean_selected_department)}" />
                        <h:commandButton type="submit" value="Cancel" action="departments" />
                    </p:panel>

         </h:form>
           
    </body>
</html>

Solutions/WebApplication/web/admin/addOrganization.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"   
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="masterTemplate.xhtml">
    
    <ui:define name="top">
        <h1>Add Organization </h1>
    </ui:define>
    
    <ui:define name="content">

        <p:panel id="panelOrg" header="Please fill in all fields and click Add">
            <h:panelGrid columns="3" style="height: 96px; width:456px;">

                <h:outputLabel value="Name:" style="font-weight: bold"/>
                <h:inputText id="nameInputText" 
                             required="true" 
                             style="width: 300px;" 
                             value="#{organizationBean.organization.name}" 
                             requiredMessage="Please enter name" 
                             validatorMessage="Name must be greater than 3 and less than 40">
                    <f:validateLength minimum="3" maximum="40" />
                </h:inputText>
                <h:message for="nameInputText" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>

                <h:outputText value="Phone:" style="font-weight: bold"/>
                <p:inputMask mask="(999) 999-9999" 
                             style="width: 300px;" 
                             id="phone"
                             value="#{organizationBean.organization.phone}"
                             required="true" 
                             requiredMessage="Please enter your phone." 
                             placeholder="Valid Phone">

                </p:inputMask>
                <h:message for="phone" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>

                <h:outputLabel value="Email:" style="font-weight: bold"/>
                <h:inputText id="emailInputText" 
                             required="true" 
                             style="width: 300px;" 
                             value="#{organizationBean.organization.email}" 
                             requiredMessage="Please enter email" 
                             validatorMessage="Invalid email format">
                    <f:validateLength minimum="3" maximum="40" />
                    <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                </h:inputText>
                <h:message for="emailInputText" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>

                <h:outputLabel value="Location:" style="font-weight: bold"/>
                <h:inputText id="locationInputText" 
                             required="true" 
                             style="width: 300px;"
                             value="#{organizationBean.organization.location}" 
                             requiredMessage="Please enter location" 
                             validatorMessage="Location must be greater than 3 and less than 60">
                    <f:validateLength minimum="3" maximum="60" />
                </h:inputText>
                <h:message for="locationInputText" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>


                <h:outputText value="Domain" style="font-weight: bold"/>
                <h:inputText id="DomainInputText" 
                             required="true" 
                             style="width: 300px;"
                             value="#{organizationBean.organization.domain}"
                             requiredMessage="Please enter domain">
                </h:inputText>
                <h:message for="DomainInputText" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>


                <h:outputLabel value="General Information" style="font-weight: bold"/>
                <h:inputTextarea id="GeneralInformationInputText" 
                                 required="true" 
                                 rows="15" 
                                 cols="40"
                                 value="#{organizationBean.organization.generalInformation}"
                                 requiredMessage="Please enter general information">
                </h:inputTextarea>
                <h:message for="GeneralInformationInputText" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>

                <h:outputText value="URL for Video" style="font-weight: bold"/>
                <h:inputText id="VideoURLInputText" 
                             required="true" 
                             style="width: 300px;"
                             value="#{organizationBean.organization.videoUrl}"
                             requiredMessage="Please enter the URL for video">
                </h:inputText>
                <h:message for="VideoURLInputText" errorClass="errorMessage" infoClass="infoMessage" warnClass="warnMessage"/>

                <h:outputLabel value="Icon:" style="font-weight: bold"/>
                <p:panelGrid columns="2">
                    <h:graphicImage id="IconImage"
                                    value="#{organizationBean.iconForAddString}" height="48px"/>
                    <p:fileUpload fileUploadListener="#{organizationBean.handleFileUploadOrganization}" 
                                  mode="advanced"
                                  auto="True" 
                                  update="IconImage" 
                                  sizeLimit="10000" 
                                  allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
                </p:panelGrid>

            </h:panelGrid>

            <p:commandButton type="submit" value="Add" action="#{organizationBean.add}" />

        </p:panel>
        
    </ui:define>
    
</ui:composition>





Solutions/WebApplication/web/admin/categories.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"   
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="masterTemplate.xhtml">

    <ui:define name="top">
        <h1> Categories </h1>
    </ui:define>

    <ui:define name="content">

        <p><p:commandButton value="Add" action="addCategory" /></p>

        <p:dataTable value="#{categoryBean.categoryList}" 
                     var="category" selectionMode="single" 
                     selection="#{categoryBean.selectedCategory}"  
                     rowKey="#{category.categoryId}" >
            <p:ajax event="rowSelect" listener="#{categoryBean.onRowSelectNavigate}"  />

            <p:column>
                <!-- column header -->
                <f:facet name="header">Name</f:facet>
                <!-- row record -->
                <h:outputText value=" #{category.name}" />

            </p:column>
                   <p:column>
                <!-- column header -->
                <f:facet name="header">Image</f:facet>
                <!-- row record -->
                <h:outputText value=" #{category.image}" />

            </p:column>
            <p:column>
                <!-- column header -->
                <f:facet name="header">Creation Date</f:facet>
                <!-- row record -->
                <h:outputText value=" #{category.createdDate}" />

            </p:column>

            <p:column>
                <!-- column header -->
                <f:facet name="header">Id</f:facet>
                <!-- row record -->
                <h:outputText value=" #{category.categoryId}" />

            </p:column>


        </p:dataTable>


    </ui:define>

</ui:composition>

Solutions/WebApplication/web/admin/categoryDetail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      > 
    <body>
        <ui:composition template="masterTemplate.xhtml">
            <ui:define name="top">
                <h1>Update category </h1>
            </ui:define>
            <ui:define name="content">


                <h:form  id="form">
                    <p:panel header="Please fill in all fields and click Add">
                        <h:panelGrid columns="2" style="height: 96px; width:456px;">
                            <h:outputText value="Name:"/>
                            <h:inputText id="nameInputText" required="true" value="#{categoryBean.selectedCategory.name}" requiredMessage="Please enter name" validatorMessage="Name must be greater than 3 and less than 40">
                                <f:validateLength minimum="3" maximum="40" />

                            </h:inputText>
                             <h:outputText value="Image:"/>
                             <h:inputText size="50" maxlength="245" id="imageInputText"  value="#{categoryBean.selectedCategory.image}">
                            
                            </h:inputText>
                        </h:panelGrid>
           
                        <p:commandButton type="submit" value="Update" action="#{categoryBean.update}" />
                    </p:panel>

                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>